import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/custom.scss'
import '@/app/bootstrap.js'
import { Content } from './Content.jsx'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='h-100'>
      <body className={clsx(inter.className, 'd-flex', 'flex-column', 'h-100')}>
        <Content>{children}</Content>
      </body>
    </html>
  )
}
